[nfs]
172.31.82.242 ansible_ssh_user='ec2-user'

[webservers]
172.31.84.97 ansible_ssh_user='ec2-user'
172.31.93.128 ansible_ssh_user='ec2-user'

[db]
172.31.84.190 ansible_ssh_user='ec2-user' 

[lb]
172.31.17.152 ansible_ssh_user='ubuntu'